"""empty message

Revision ID: 5e5f6ca864b9
Revises: 73b4b23e011a
Create Date: 2023-06-19 15:57:41.532612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5f6ca864b9'
down_revision = '73b4b23e011a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_poster_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recipes_poster_id_users'), 'users', ['poster_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_poster_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_recipes_poster_id_users', 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###
